from pathlib import Path

lines = []
lines.append('// master_loop_scada_v20_static.js')
lines.append('// Versi ES5 untuk Haiwell SCADA dengan akses statik per-unit ke tag HMI.')
lines.append('// Trigger: Timer 1 Detik (1000ms)')
lines.append('')
lines.append('// 1. Ekstrak Waktu Sistem (Format HH:MM:SS)')
lines.append('var waktuSekarangString = ("0" + ($Hour || 0)).slice(-2) + ":" + ("0" + ($Minute || 0)).slice(-2) + ":" + ("0" + ($Second || 0)).slice(-2);')
lines.append('var totalDetikSekarang = (($Hour || 0) * 3600) + (($Minute || 0) * 60) + ($Second || 0);')
lines.append('')
lines.append('// 2. Auto-Inisialisasi / Tulis Default ke Tag HMI jika Kosong')
for name, value in [
    ('txt_status_kosong', 'STEAMBOX KOSONG'),
    ('txt_status_preheat', 'SEDANG PEMANASAN'),
    ('txt_status_pemanasan', 'MENUNGGU MENDIDIH (< 100 C)'),
    ('txt_status_pemasakan', 'SEDANG MEMASAK (MENDIDIH)'),
    ('txt_status_selesai', 'PROSES SELESAI - SILAKAN KOSONGKAN TANGKI'),
    ('txt_selesai_preheat', 'PEMANASAN SELESAI - STEAMBOX SIAP UNTUK PEMASAKAN'),
    ('txt_siap_preheat', 'SIAP PEMANASAN - SILAKAN TEKAN START'),
    ('txt_siap_cooking', 'RESEP TERPASANG - SILAKAN TEKAN START'),
    ('txt_status_resep', 'RESEP TERPASANG - SILAKAN TEKAN START'),
    ('txt_preheat_paused', 'PRE-HEAT DIHENTIKAN (PAUSED)'),
    ('txt_status_paused', 'MESIN BERHENTI (PAUSED)'),
    ('txt_status_maintenance', 'MODE MAINTENANCE (KONTROL MANUAL)'),
    ('txt_status_offline', 'KONEKSI OFFLINE (MCB TRIP/ALAT MATI)'),
    ('txt_status_disable', 'UNIT TIDAK DIPAKAI'),
    ('txt_status_sensor_error', 'ERROR SENSOR (OPENLOOP/HHHH)'),
    ('txt_sensor_error', 'proses memasak, tetapi sensor error, cek segera !'),
]:
    lines.append(f'$Sys_Control.{name} = $Sys_Control.{name} || "{value}";')
lines.append('')
for alias, name in [
    ('txtKosong', 'txt_status_kosong'),
    ('txtPreheat', 'txt_status_preheat'),
    ('txtPemanasan', 'txt_status_pemanasan'),
    ('txtPemasakan', 'txt_status_pemasakan'),
    ('txtSelesai', 'txt_status_selesai'),
    ('txtSelesaiPreheat', 'txt_selesai_preheat'),
    ('txtSiapPreheat', 'txt_siap_preheat'),
    ('txtSiapCooking', 'txt_siap_cooking'),
    ('txtStatusResep', 'txt_status_resep'),
    ('txtPreheatPaused', 'txt_preheat_paused'),
    ('txtPaused', 'txt_status_paused'),
    ('txtMaintenance', 'txt_status_maintenance'),
    ('txtOffline', 'txt_status_offline'),
    ('txtDisable', 'txt_status_disable'),
    ('txtSensorError', 'txt_status_sensor_error'),
    ('txtSensorErrorCooking', 'txt_sensor_error'),
]:
    lines.append(f'var {alias} = $Sys_Control.{name};')
lines.append('var tempErrorLimit = $Sys_Control.temp_error_limit || 30000;')
lines.append('')
lines.append('// Helper function format durasi')
lines.append('function formatTime(totalSeconds) {')
lines.append('    var h = Math.floor(totalSeconds / 3600);')
lines.append('    var m = Math.floor((totalSeconds % 3600) / 60);')
lines.append('    var s = totalSeconds % 60;')
lines.append('    return ("0" + h).slice(-2) + ":" + ("0" + m).slice(-2) + ":" + ("0" + s).slice(-2);')
lines.append('}')
lines.append('')
lines.append('// Helper function estimasi jam selesai')
lines.append('function getEstimasiSelesai(totalDetikSekarang, sisa) {')
lines.append('    var est = (totalDetikSekarang + sisa) % 86400;')
lines.append('    var he = Math.floor(est / 3600);')
lines.append('    var me = Math.floor((est % 3600) / 60);')
lines.append('    var se = est % 60;')
lines.append('    return ("0" + he).slice(-2) + ":" + ("0" + me).slice(-2) + ":" + ("0" + se).slice(-2);')
lines.append('}')
lines.append('')
lines.append('// Reset Global Trigger Log (Untuk Data Group Log_Steambox)')
lines.append('if ($Sys_Control.trigger_log) {')
lines.append('    $Sys_Control.trigger_log = false;')
lines.append('}')
lines.append('')
lines.append('var sbUnits = [null,')
for i in range(1, 31):
    comma = ',' if i < 30 else ''
    lines.append(f'    $sb_{i}{comma}')
lines.append('];')
lines.append('var devUnits = [null,')
for i in range(1, 31):
    comma = ',' if i < 30 else ''
    lines.append(f'    $sb{i}{comma}')
lines.append('];')
lines.append('')
lines.append('function getRecipeValues(i) {')
lines.append('    switch (i) {')
for i in range(1, 31):
    lines.append(f'        case {i}:')
    lines.append('            return {')
    lines.append(f'                kode: this["$recipe_kode.{i}"],')
    lines.append(f'                nama: this["$recipe_nama.{i}"],')
    lines.append(f'                versi: this["$recipe_versi.{i}"],')
    lines.append(f'                batch: this["$recipe_batch.{i}"],')
    lines.append(f'                warna: this["$recipe_warna.{i}"],')
    lines.append(f'                qty: this["$recipe_qty.{i}"],')
    lines.append(f'                trolly: this["$recipe_trolly.{i}"]')
    lines.append('            };')
lines.append('        default:')
lines.append('            return { kode: "", nama: "--", versi: 0, batch: 0, warna: "", qty: 0, trolly: "" };')
lines.append('    }')
lines.append('}')
lines.append('')
lines.append('function resetRecipeValues(i) {')
lines.append('    switch (i) {')
for i in range(1, 31):
    lines.append(f'        case {i}:')
    lines.append(f'            this["$recipe_kode.{i}"] = "";')
    lines.append(f'            this["$recipe_nama.{i}"] = "--";')
    lines.append(f'            this["$recipe_versi.{i}"] = 0;')
    lines.append(f'            this["$recipe_warna.{i}"] = "";')
    lines.append(f'            this["$recipe_qty.{i}"] = 0;')
    lines.append(f'            this["$recipe_batch.{i}"] = 0;')
    lines.append(f'            this["$recipe_trolly.{i}"] = "";')
    lines.append('            break;')
lines.append('    }')
lines.append('}')
lines.append('')
lines.append('function resetUnit(i, sb) {')
lines.append('    if (!sb.reset) {')
lines.append('        return false;')
lines.append('    }')
lines.append('    sb.status_selesai = false;')
lines.append('    sb.flag_init_masak = 0;')
lines.append('    sb.total_detik_pemanasan = 0;')
lines.append('    sb.sisa_detik_masak = 0;')
lines.append('    sb.target_menit = 0;')
lines.append('    sb.adjust_menit = 0;')
lines.append('    sb.tampil_jam_mulai = "--:--:--";')
lines.append('    sb.tampil_jam_masak = "--:--:--";')
lines.append('    sb.tampil_jam_selesai = "--:--:--";')
lines.append('    sb.tampil_durasi_aktual = "--";')
lines.append('    sb.durasi_aktual_up = "--";')
lines.append('    sb.tampil_pemanasan = "--:--:--";')
lines.append('    sb.suhu_awal = 0;')
lines.append('    sb.suhu_akhir = 0;')
lines.append('    sb.perubahan_waktu = 0;')
lines.append('    sb.status_kosong = true;')
lines.append('    sb.status_resep = false;')
lines.append('    sb.mode_preheat = false;')
lines.append('    sb.flag_init_start = 0;')
lines.append('    sb.status_banner = txtKosong;')
lines.append('    sb.reset = false;')
lines.append('    resetRecipeValues(i);')
lines.append('    return true;')
lines.append('}')
lines.append('')
lines.append('function pushFinishedData(i, sb, recipeValues, finalDurasiUpStr, finalJamSelesaiStr, activePerubahan) {')
lines.append('    $data_group_master.no_steambox = i;')
lines.append('    $data_group_master.kode = recipeValues.kode;')
lines.append('    $data_group_master.nama = recipeValues.nama;')
lines.append('    $data_group_master.versi = recipeValues.versi;')
lines.append('    $data_group_master.batch = recipeValues.batch;')
lines.append('    $data_group_master.warna = recipeValues.warna;')
lines.append('    $data_group_master.qty = recipeValues.qty;')
lines.append('    $data_group_master.trolly = recipeValues.trolly;')
lines.append('    $data_group_master.durasi = sb.target_menit;')
lines.append('    $data_group_master.jam_mulai = sb.tampil_jam_mulai;')
lines.append('    $data_group_master.durasi_pemanasan = sb.tampil_pemanasan;')
lines.append('    $data_group_master.jam_masak = sb.tampil_jam_masak;')
lines.append('    $data_group_master.durasi_aktual = finalDurasiUpStr;')
lines.append('    $data_group_master.jam_selesai = finalJamSelesaiStr;')
lines.append('    $data_group_master.perubahan_waktu = activePerubahan;')
lines.append('    $data_group_master.suhu_awal = sb.suhu_awal;')
lines.append('    $data_group_master.suhu_akhir = sb.suhu_akhir;')
lines.append('    $data_group_master.status = "SUCCESS";')
lines.append('    $Sys_Control.trigger_log = true;')
lines.append('}')
lines.append('')
lines.append('function updateUnitState(i, totalDetikSekarang, runningRooms) {')
lines.append('    var sb = sbUnits[i];')
lines.append('    var dev = devUnits[i];')
lines.append('    if (!sb || !dev) {')
lines.append('        return;')
lines.append('    }')
lines.append('    var recipeValues = getRecipeValues(i);')
lines.append('    var activeSisa = sb.sisa_detik_masak || 0;')
lines.append('    var activePerubahan = sb.perubahan_waktu || 0;')
lines.append('    var scale_up = 0;')
lines.append('')
lines.append('    if (sb.adjust_menit !== 0) {')
lines.append('        var adjustSecs = sb.adjust_menit * 60;')
lines.append('        activeSisa = activeSisa + adjustSecs;')
lines.append('        if (activeSisa < 0) {')
lines.append('            activeSisa = 0;')
lines.append('        }')
lines.append('        sb.sisa_detik_masak = activeSisa;')
lines.append('        activePerubahan = activePerubahan + sb.adjust_menit;')
lines.append('        sb.perubahan_waktu = activePerubahan;')
lines.append('        sb.adjust_menit = 0;')
lines.append('    }')
lines.append('')
lines.append('    if (!dev._commOperation) {')
lines.append('        sb.status_banner = txtDisable;')
lines.append('        sb.status_pemanasan = false;')
lines.append('        sb.status_pemasakan = false;')
lines.append('        sb.status_selesai = false;')
lines.append('        sb.sensor_error = false;')
lines.append('        return;')
lines.append('    }')
lines.append('')
lines.append('    if (!dev._commStatus) {')
lines.append('        sb.status_banner = txtOffline;')
lines.append('        sb.status_pemanasan = false;')
lines.append('        sb.status_pemasakan = false;')
lines.append('        sb.status_selesai = false;')
lines.append('        sb.sensor_error = false;')
lines.append('        return;')
lines.append('    }')
lines.append('')
lines.append('    if (sb.maintenance_mode) {')
lines.append('        sb.status_banner = txtMaintenance;')
lines.append('        sb.sensor_error = false;')
lines.append('        return;')
lines.append('    }')
lines.append('')
lines.append('    var isSensorError = (dev.temp >= tempErrorLimit);')
lines.append('')
lines.append('    if (Number(dev.run_stop) === 1) {')
lines.append('        sb.status_pemanasan = false;')
lines.append('        sb.status_pemasakan = false;')
lines.append('        if (sb.mode_preheat || sb.status_resep) {')
lines.append('            sb.status_kosong = false;')
lines.append('        }')
lines.append('        if (!sb.mode_preheat && !sb.status_resep && sb.target_menit === 0 && activeSisa === 0 && !sb.status_selesai && sb.total_detik_pemanasan === 0) {')
lines.append('            sb.status_kosong = true;')
lines.append('        }')
lines.append('        if (sb.status_kosong) {')
lines.append('            sb.status_banner = txtKosong;')
lines.append('        } else if (sb.status_selesai) {')
lines.append('            sb.status_banner = txtSelesai;')
lines.append('        } else if (!sb.status_kosong && !sb.status_selesai && !sb.mode_preheat && !sb.status_resep) {')
lines.append('            sb.status_banner = txtSelesaiPreheat;')
lines.append('        } else {')
lines.append('            if (sb.mode_preheat) {')
lines.append('                if (sb.total_detik_pemanasan === 0) {')
lines.append('                    sb.status_banner = txtSiapPreheat;')
lines.append('                } else {')
lines.append('                    sb.status_banner = txtPreheatPaused;')
lines.append('                }')
lines.append('            } else {')
lines.append('                if (sb.status_resep && activeSisa === 0) {')
lines.append('                    sb.status_banner = txtStatusResep;')
lines.append('                } else {')
lines.append('                    sb.status_banner = txtPaused;')
lines.append('                }')
lines.append('            }')
lines.append('        }')
lines.append('        if (sb.flag_init_start === 1 && Number(sb.status_selesai) === 0) {')
lines.append('            sb.tampil_durasi_aktual = formatTime(activeSisa);')
lines.append('            scale_up = (((sb.target_menit || 0) + activePerubahan) * 60) - activeSisa;')
lines.append('            sb.durasi_aktual_up = formatTime(scale_up < 0 ? 0 : scale_up);')
lines.append('            if (sb.flag_init_masak === 1) {')
lines.append('                sb.tampil_jam_selesai = getEstimasiSelesai(totalDetikSekarang, activeSisa);')
lines.append('            }')
lines.append('        }')
lines.append('    } else {')
lines.append('        sb.status_kosong = false;')
lines.append('        if (sb.mode_preheat) {')
lines.append('            sb.status_pemanasan = false;')
lines.append('            sb.status_pemasakan = false;')
lines.append('            sb.status_banner = txtPreheat;')
lines.append('            if (sb.flag_init_start === 0) {')
lines.append('                sb.status_selesai = false;')
lines.append('                sb.tampil_jam_mulai = "--:--:--";')
lines.append('                sb.tampil_jam_masak = "--:--:--";')
lines.append('                sb.tampil_jam_selesai = "--:--:--";')
lines.append('                sb.tampil_durasi_aktual = "--";')
lines.append('                sb.durasi_aktual_up = "--";')
lines.append('                sb.flag_init_start = 1;')
lines.append('                sb.total_detik_pemanasan = 0;')
lines.append('                sb.suhu_awal = dev.temp;')
lines.append('                activePerubahan = 0;')
lines.append('                sb.perubahan_waktu = 0;')
lines.append('            }')
lines.append('            sb.total_detik_pemanasan = sb.total_detik_pemanasan + 1;')
lines.append('            sb.tampil_pemanasan = formatTime(sb.total_detik_pemanasan);')
lines.append('            if (dev.temp > 1000) {')
lines.append('                dev.run_stop = 1;')
lines.append('                sb.status_pemanasan = false;')
lines.append('                sb.suhu_akhir = dev.temp;')
lines.append('                sb.flag_init_start = 0;')
lines.append('                sb.mode_preheat = false;')
lines.append('            }')
lines.append('        } else {')
lines.append('            if (sb.flag_init_start === 0) {')
lines.append('                sb.status_selesai = false;')
lines.append('                sb.tampil_jam_mulai = waktuSekarangString;')
lines.append('                sb.tampil_jam_masak = "--:--:--";')
lines.append('                sb.tampil_jam_selesai = "--:--:--";')
lines.append('                sb.flag_init_start = 1;')
lines.append('                activeSisa = sb.target_menit * 60;')
lines.append('                sb.sisa_detik_masak = activeSisa;')
lines.append('                sb.total_detik_pemanasan = 0;')
lines.append('                sb.flag_init_masak = 0;')
lines.append('                sb.suhu_awal = dev.temp;')
lines.append('                activePerubahan = 0;')
lines.append('                sb.perubahan_waktu = 0;')
lines.append('            }')
lines.append('            if (dev.temp < 1000) {')
lines.append('                sb.status_pemanasan = true;')
lines.append('                sb.status_pemasakan = false;')
lines.append('                sb.status_banner = txtPemanasan;')
lines.append('                sb.total_detik_pemanasan = sb.total_detik_pemanasan + 1;')
lines.append('                sb.tampil_pemanasan = formatTime(sb.total_detik_pemanasan);')
lines.append('                sb.tampil_durasi_aktual = formatTime(activeSisa);')
lines.append('                var detik_up_heat = (((sb.target_menit || 0) + activePerubahan) * 60) - activeSisa;')
lines.append('                sb.durasi_aktual_up = formatTime(detik_up_heat < 0 ? 0 : detik_up_heat);')
lines.append('                if (sb.flag_init_masak === 1) {')
lines.append('                    sb.tampil_jam_selesai = getEstimasiSelesai(totalDetikSekarang, activeSisa);')
lines.append('                    runningRooms.push({ name: i, sisa: activeSisa, tampilSisa: sb.tampil_durasi_aktual, tampilSelesai: sb.tampil_jam_selesai });')
lines.append('                } else {')
lines.append('                    sb.tampil_jam_selesai = "--:--:--";')
lines.append('                }')
lines.append('            } else {')
lines.append('                sb.status_pemanasan = false;')
lines.append('                sb.status_pemasakan = true;')
lines.append('                sb.status_banner = txtPemasakan;')
lines.append('                if (sb.flag_init_masak === 0) {')
lines.append('                    sb.tampil_jam_masak = waktuSekarangString;')
lines.append('                    sb.flag_init_masak = 1;')
lines.append('                }')
lines.append('                if (activeSisa > 0) {')
lines.append('                    activeSisa = activeSisa - 1;')
lines.append('                    sb.sisa_detik_masak = activeSisa;')
lines.append('                }')
lines.append('                sb.tampil_durasi_aktual = formatTime(activeSisa);')
lines.append('                var detik_up_boil = (((sb.target_menit || 0) + activePerubahan) * 60) - activeSisa;')
lines.append('                sb.durasi_aktual_up = formatTime(detik_up_boil < 0 ? 0 : detik_up_boil);')
lines.append('                if (activeSisa <= 0) {')
lines.append('                    activeSisa = 0;')
lines.append('                    sb.sisa_detik_masak = 0;')
lines.append('                    sb.tampil_durasi_aktual = formatTime(0);')
lines.append('                    var finalDurasiUpStr = formatTime(((sb.target_menit || 0) + activePerubahan) * 60);')
lines.append('                    sb.durasi_aktual_up = finalDurasiUpStr;')
lines.append('                    var finalJamSelesaiStr = getEstimasiSelesai(totalDetikSekarang, 0);')
lines.append('                    sb.tampil_jam_selesai = finalJamSelesaiStr;')
lines.append('                    sb.suhu_akhir = dev.temp;')
lines.append('                    dev.run_stop = 1;')
lines.append('                    sb.status_pemasakan = false;')
lines.append('                    sb.flag_init_start = 0;')
lines.append('                    sb.flag_init_masak = 0;')
lines.append('                    pushFinishedData(i, sb, recipeValues, finalDurasiUpStr, finalJamSelesaiStr, activePerubahan);')
lines.append('                    sb.status_selesai = true;')
lines.append('                } else {')
lines.append('                    sb.tampil_jam_selesai = getEstimasiSelesai(totalDetikSekarang, activeSisa);')
lines.append('                    runningRooms.push({ name: i, sisa: activeSisa, tampilSisa: sb.tampil_durasi_aktual, tampilSelesai: sb.tampil_jam_selesai });')
lines.append('                }')
lines.append('            }')
lines.append('        }')
lines.append('    }')
lines.append('    if (isSensorError) {')
lines.append('        sb.sensor_error = true;')
lines.append('        if (Number(dev.run_stop) === 0 && sb.flag_init_start === 1) {')
lines.append('            sb.status_banner = txtSensorErrorCooking;')
lines.append('        } else {')
lines.append('            sb.status_banner = txtSensorError;')
lines.append('        }')
lines.append('    } else {')
lines.append('        sb.sensor_error = false;')
lines.append('    }')
lines.append('}')
lines.append('')
lines.append('var runningRooms = [];')
lines.append('for (var i = 1; i <= 30; i++) {')
lines.append('    var sb = sbUnits[i];')
lines.append('    if (!sb) {')
lines.append('        continue;')
lines.append('    }')
lines.append('    if (resetUnit(i, sb)) {')
lines.append('        continue;')
lines.append('    }')
lines.append('    updateUnitState(i, totalDetikSekarang, runningRooms);')
lines.append('}')

Path('master_loop_scada_v20_static.js').write_text('\n'.join(lines), encoding='utf-8')
print('Generated master_loop_scada_v20_static.js')
